name: hex_api
version: 1.0.0
description: hex_api - OpenAPI spec
homepage: https://swagger.io/

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  dio: "^5.7.0"
  json_annotation: "^4.9.0"

dev_dependencies:
  build_runner: any
  json_serializable: "^6.9.3"
  test: "^1.16.0"
