// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_hex_pm/test/screens/offline_docs/offline_docs_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i2;

import 'package:bloc/bloc.dart' as _i6;
import 'package:hex_doc_bloc/src/bloc.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDirectory_0 extends _i1.SmartFake implements _i2.Directory {
  _FakeDirectory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHexDocState_1 extends _i1.SmartFake implements _i3.HexDocState {
  _FakeHexDocState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HexDocBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHexDocBloc extends _i1.Mock implements _i3.HexDocBloc {
  MockHexDocBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Directory get appSupportDir => (super.noSuchMethod(
        Invocation.getter(#appSupportDir),
        returnValue: _FakeDirectory_0(
          this,
          Invocation.getter(#appSupportDir),
        ),
      ) as _i2.Directory);

  @override
  _i2.Directory get tmpDir => (super.noSuchMethod(
        Invocation.getter(#tmpDir),
        returnValue: _FakeDirectory_0(
          this,
          Invocation.getter(#tmpDir),
        ),
      ) as _i2.Directory);

  @override
  _i3.HexDocState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHexDocState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.HexDocState);

  @override
  _i4.Stream<_i3.HexDocState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.HexDocState>.empty(),
      ) as _i4.Stream<_i3.HexDocState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String getUrl(
    String? name,
    String? version,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [
            name,
            version,
          ],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getUrl,
            [
              name,
              version,
            ],
          ),
        ),
      ) as String);

  @override
  void add(_i3.HexDocEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i3.HexDocEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.HexDocState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i3.HexDocEvent>(
    _i6.EventHandler<E, _i3.HexDocState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i6.Transition<_i3.HexDocEvent, _i3.HexDocState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onChange(_i6.Change<_i3.HexDocState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
