arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/l10n/gen_l10n
output-localization-file: feedback_localizations.dart
output-class: FeedbackLocalizations
nullable-getter: false
synthetic-package: false
