import "../../scripts/Fastfile"

default_platform(:ios)

platform :ios do
  # Private lanes
  private_lane :archive do |options|
    method = options[:method]
    profile_name = method == 'ad-hoc' ? "Distribution - Staging (adhoc)" : "Production"
    update_code_signing_settings(profile_name: profile_name)
    build_app(export_method: method)
  end

  private_lane :authenticate_apple_store do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_IDENTIFIER"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      duration: 1200,
      in_house: false,
    )
  end

  # Public lanes
  lane :build do |options|
    fetch_dependencies
    sign_enabled = options[:sign_enabled] || false
    sign_param = sign_enabled ? '' : '--no-codesign'
    config_only = options[:config_only] || false
    config_param = config_only ? '--config-only' : ''
    sh_on_root(command: "flutter build ipa --build-number #{ENV["CI_BUILD_NUMBER"]} --no-pub --release #{sign_param} #{config_param}")
  end

  lane :deploy_staging do
    build(sign_enabled: true)
    authenticate_apple_store
    upload_to_testflight(
      ipa: "#{root_path}/build/ios/ipa/mobile_hex_pm.ipa",
      reject_build_waiting_for_review: true,
      skip_waiting_for_build_processing: true,
      distribute_external: true,
      notify_external_testers: true,
      groups: ["gsmlg"],
      changelog: "",
    )
  end

  lane :deploy_production do
    build(sign_enabled: true, config_only: true)
    archive(method: "app-store")
    authenticate_apple_store
    deliver(
      ipa: "#{root_path}/build/ios/ipa/mobile_hex_pm.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      force: false,
      automatic_release: false,
      submission_information: {
        add_id_info_serves_ads: false,
        add_id_info_uses_idfa: false,
        export_compliance_uses_encryption: false,
      },
      precheck_include_in_app_purchases: false,
      uses_non_exempt_encryption: true,
      skip_waiting_for_build_processing: true,
    )
  end
end
