name: Build apk

on:
  workflow_dispatch:
    inputs:
      build-name:
        required: true
        description: |
            The version of the release, provide by `--build-name=<x.y.z>`,
            the push apk to release tag {github.event.inputs.build-name}.
        default: '0.1.0'
      revision:
        required: true
        description: 'The revision of git'
        default: 'main'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.revision }}

      - uses: flutter-actions/setup-flutter@v3

      - name: Install tools
        run: dart pub global activate melos
        
      - name: Install dependencies
        run: melos run prepare

      - name: Build apk
        run: flutter build apk --build-name=${{ github.event.inputs.build-name }} --release

      - name: ⬆️ Upload api to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.build-name }}
          file: "build/app/outputs/flutter-apk/app-release.apk"
          overwrite: true
          file_glob: true
