name: theme_bloc
description: App theme bloc
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17

  app_theme: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
